
language: python
python:
  - "3.6"
# command to run tests
script:
  - bash scripts/run_tests.sh
deploy:
  provider: script
  skip_cleanup: true
  script:
    - bash scripts/tag.sh
  on:
    branch: master
notifications:
  email:
    on_success: never
    on_failure: always
